JOB_TYPES = {
    'Real Estate': [
        'Home',
        'Land',
        'Inspection',
        'Appraisal',
        'Survey',
        'Other'
    ],
    'Natural Resources': [
        'Agriculture',
        'Forestry',
        'Geology',
        'Wildlife',
        'Fisheries',
        'Mining',
        'Aquatics',
        'Recreation',
        'Research',
        'Other'
    ],
    'Infrastructure': [
        'Roads',
        'Highways',
        'Interstates',
        'Bridges',
        'Railways',
        'Seaways',
        'Utilities',
        'Telecommunications',
        'Other'
    ],
    'Energy': [
        'Gas/Oil',
        'Hydroelectric',
        'Wind',
        'Solar',
        'Natural Gas',
        'Geothermal',
        'Coal',
        'Nuclear',
        'Other'
    ],
    'Natural Disaster': [
        'Structural Fire',
        'Wildland Fire',
        'Hurricane',
        'Tornado',
        'Blizzard',
        'Earthquake',
        'Tsunami',
        'Avalanche',
        'Flooding',
        'Volcano',
        'Thunderstorm',
        'Dust Storm',
        'Wind Storm',
        'General FEMA',
        'Other'
    ],
    'Event': [
        'Wedding',
        'Concert',
        'Festival',
        'Sports',
        'Conference',
        'Gathering',
        'Fair',
        'Community',
        'Birthday',
        'Holiday',
        'Anniversary',
        'Retirement',
        'Funeral',
        'Other'
    ],
    'LIDAR': [
        'Terrestrial',
        'Aerial',
        'Other'
    ],
    'Insurance': [
        'Inspection',
        'Appraisal',
        'Claim',
        'Other'
    ],
    'General Photo/Video': [
        'Film',
        'Photography',
        'News',
        'Social Media',
        'Academics',
        'Advertising',
        'Personal',
        'Other'
    ]
}


METROS = {
    'Alaska': [
        'Anchorage',
        'Fairbanks',
    ],
    'Alabama': [
        'Albertville',
        'Anniston-Oxford',
        'Auburn-Opelika',
        'Birmingham-Hoover',
        'Columbus',
        'Cullman',
        'Daphne-Fairhope-Foley',
        'Decatur',
        'Dothan',
        'Florence-Muscle Shoals',
        'Gadsden',
        'Huntsville',
        'Mobile',
        'Montgomery',
        'Talladega-Sylacauga',
        'Tuscaloosa',
    ],
    'Arkansas': [
        'Fayetteville-Springdale-Rogers',
        'Fort Smith',
        'Hot Springs',
        'Jonesboro',
        'Little Rock-North Little Rock-Conway',
        'Memphis',
        'Pine Bluff',
        'Russellville',
        'Searcy',
        'Texarkana',
    ],
    'Arizona': [
        'Flagstaff',
        'Lake Havasu City-Kingman',
        'Phoenix-Mesa-Chandler',
        'Show Low',
        'Sierra Vista-Douglas',
        'Tucson',
        'Yuma',
    ],
    'California': [
        'Bakersfield',
        'Chico',
        'El Centro',
        'Eureka-Arcata',
        'Fresno',
        'Hanford-Corcoran',
        'Los Angeles-Long Beach-Anaheim',
        'Madera',
        'Merced',
        'Modesto',
        'Napa',
        'Oxnard-Thousand Oaks-Ventura',
        'Redding',
        'Riverside-San Bernardino-Ontario',
        'Sacramento-Roseville-Folsom',
        'Salinas',
        'San Diego-Chula Vista-Carlsbad',
        'San Francisco-Oakland-Berkeley',
        'San Jose-Sunnyvale-Santa Clara',
        'San Luis Obispo-Paso Robles',
        'Santa Cruz-Watsonville',
        'Santa Maria-Santa Barbara',
        'Santa Rosa-Petaluma',
        'Stockton',
        'Truckee-Grass Valley',
        'Ukiah',
        'Vallejo',
        'Visalia',
        'Yuba City',
    ],
    'Colorado': [
        'Boulder',
        'Colorado Springs',
        'Denver-Aurora-Lakewood',
        'Fort Collins',
        'Glenwood Springs',
        'Grand Junction',
        'Greeley',
        'Pueblo',
    ],
    'Connecticut': [
        'Bridgeport-Stamford-Norwalk',
        'Hartford-East Hartford-Middletown',
        'New Haven-Milford',
        'Norwich-New London',
        'Torrington',
        'Worcester',
    ],
    'Delaware': [
        'Dover',
        'Salisbury',
    ],
    'Florida': [
        'Cape Coral-Fort Myers',
        'Crestview-Fort Walton Beach-Destin',
        'Deltona-Daytona Beach-Ormond Beach',
        'Gainesville',
        'Homosassa Springs',
        'Jacksonville',
        'Key West',
        'Lakeland-Winter Haven',
        'Miami-Fort Lauderdale-Pompano Beach',
        'Naples-Marco Island',
        'North Port-Sarasota-Bradenton',
        'Ocala',
        'Orlando-Kissimmee-Sanford',
        'Palatka',
        'Palm Bay-Melbourne-Titusville',
        'Panama City',
        'Pensacola-Ferry Pass-Brent',
        'Port St. Lucie',
        'Punta Gorda',
        'Sebastian-Vero Beach',
        'Sebring-Avon Park',
        'Tallahassee',
        'Tampa-St. Petersburg-Clearwater',
        'The Villages',
    ],
    'Georgia': [
        'Albany',
        'Athens-Clarke County',
        'Atlanta-Sandy Springs-Alpharetta',
        'Augusta-Richmond County',
        'Brunswick',
        'Chattanooga',
        'Columbus',
        'Dalton',
        'Gainesville',
        'Hinesville',
        'Macon-Bibb County',
        'Rome',
        'Savannah',
        'Statesboro',
        'Valdosta',
        'Warner Robins',
    ],
    'Hawaii': [
        'Hilo',
        'Kahului-Wailuku-Lahaina',
        'Urban Honolulu',
    ],
    'Iowa': [
        'Ames',
        'Cedar Rapids',
        'Davenport-Moline-Rock Island',
        'Des Moines-West Des Moines',
        'Dubuque',
        'Iowa City',
        'Omaha-Council Bluffs',
        'Sioux City',
        'Waterloo-Cedar Falls',
    ],
    'Idaho': [
        'Boise City',
        "Coeur d'Alene",
        'Idaho Falls',
        'Logan',
        'Pocatello',
        'Twin Falls',
    ],
    'Illinois': [
        'Bloomington',
        'Cape Girardeau',
        'Carbondale-Marion',
        'Champaign-Urbana',
        'Chicago-Naperville-Elgin',
        'Danville',
        'Davenport-Moline-Rock Island',
        'Decatur',
        'Kankakee',
        'Paducah',
        'Peoria',
        'Quincy',
        'Rockford',
        'St. Louis',
        'Springfield',
    ],
    'Indiana': [
        'Bloomington',
        'Cincinnati',
        'Columbus',
        'Elkhart-Goshen',
        'Evansville',
        'Fort Wayne',
        'Indianapolis-Carmel-Anderson',
        'Kokomo',
        'Lafayette-West Lafayette',
        'Louisville/Jefferson County',
        'Michigan City-La Porte',
        'Muncie',
        'South Bend-Mishawaka',
        'Terre Haute',
        'Warsaw',
    ],
    'Kansas': [
        'Kansas City',
        'Lawrence',
        'Manhattan',
        'St. Joseph',
        'Topeka',
        'Wichita',
    ],
    'Kentucky': [
        'Bowling Green',
        'Clarksville',
        'Elizabethtown-Fort Knox',
        'Evansville',
        'Frankfort',
        'Lexington-Fayette',
        'London',
        'Louisville/Jefferson County',
        'Owensboro',
        'Paducah',
        'Richmond-Berea',
    ],
    'Louisiana': [
        'Alexandria',
        'Baton Rouge',
        'Hammond',
        'Houma-Thibodaux',
        'Lafayette',
        'Lake Charles',
        'Monroe',
        'New Orleans-Metairie',
        'Opelousas',
        'Shreveport-Bossier City',
    ],
    'Massachusetts': [
        'Barnstable Town',
        'Boston-Cambridge-Newton',
        'Pittsfield',
        'Providence-Warwick',
        'Springfield',
        'Worcester',
    ],
    'Maryland': [
        'Baltimore-Columbia-Towson',
        'California-Lexington Park',
        'Cumberland',
        'Hagerstown-Martinsburg',
        'Philadelphia-Camden-Wilmington',
        'Salisbury',
    ],
    'Maine': [
        'Augusta-Waterville',
        'Bangor',
        'Lewiston-Auburn',
        'Portland-South Portland',
    ],
    'Michigan': [
        'Adrian',
        'Ann Arbor',
        'Battle Creek',
        'Bay City',
        'Detroit-Warren-Dearborn',
        'Flint',
        'Grand Rapids-Kentwood',
        'Holland',
        'Jackson',
        'Kalamazoo-Portage',
        'Lansing-East Lansing',
        'Midland',
        'Monroe',
        'Muskegon',
        'Niles',
        'Saginaw',
        'South Bend-Mishawaka',
        'Traverse City',
    ],
    'Minnesota': [
        'Brainerd',
        'Duluth',
        'Fargo',
        'Grand Forks',
        'La Crosse-Onalaska',
        'Mankato',
        'Minneapolis-St. Paul-Bloomington',
        'Rochester',
        'St. Cloud',
    ],
    'Missouri': [
        'Branson',
        'Cape Girardeau',
        'Columbia',
        'Jefferson City',
        'Joplin',
        'Kansas City',
        'Quincy',
        'St. Joseph',
        'St. Louis',
        'Springfield',
    ],
    'Mississippi': [
        'Gulfport-Biloxi',
        'Hattiesburg',
        'Jackson',
        'Laurel',
        'Meridian',
        'Tupelo',
    ],
    'Montana': [
        'Billings',
        'Bozeman',
        'Great Falls',
        'Helena',
        'Kalispell',
        'Missoula',
    ],
    'North Carolina': [
        'Asheville',
        'Burlington',
        'Charlotte-Concord-Gastonia',
        'Durham-Chapel Hill',
        'Fayetteville',
        'Goldsboro',
        'Greensboro-High Point',
        'Greenville',
        'Hickory-Lenoir-Morganton',
        'Jacksonville',
        'Lumberton',
        'Myrtle Beach-Conway-North Myrtle Beach',
        'New Bern',
        'Pinehurst-Southern Pines',
        'Raleigh-Cary',
        'Roanoke Rapids',
        'Rocky Mount',
        'Shelby',
        'Virginia Beach-Norfolk-Newport News',
        'Wilmington',
        'Wilson',
        'Winston-Salem',
    ],
    'North Dakota': [
        'Bismarck',
        'Fargo',
        'Grand Forks',
        'Minot',
    ],
    'Nebraska': [
        'Grand Island',
        'Lincoln',
        'Omaha-Council Bluffs',
    ],
    'New Hampshire': [
        'Boston-Cambridge-Newton',
        'Concord',
        'Keene',
        'Manchester-Nashua',
    ],
    'New Jersey': [
        'Allentown-Bethlehem-Easton',
        'Atlantic City-Hammonton',
        'Ocean City',
        'Trenton-Princeton',
        'Vineland-Bridgeton',
    ],
    'New Mexico': [
        'Albuquerque',
        'Farmington',
        'Las Cruces',
        'Santa Fe',
    ],
    'Nevada': [
        'Las Vegas-Henderson-Paradise',
        'Reno',
    ],
    'New York': [
        'Albany-Schenectady-Troy',
        'Auburn',
        'Binghamton',
        'Buffalo-Cheektowaga',
        'Corning',
        'Elmira',
        'Glens Falls',
        'Ithaca',
        'Jamestown-Dunkirk-Fredonia',
        'Kingston',
        'New York-Newark-Jersey City',
        'Ogdensburg-Massena',
        'Olean',
        'Plattsburgh',
        'Rochester',
        'Syracuse',
        'Utica-Rome',
        'Watertown-Fort Drum',
    ],
    'Ohio': [
        'Akron',
        'Ashtabula',
        'Canton-Massillon',
        'Chillicothe',
        'Cincinnati',
        'Cleveland-Elyria',
        'Columbus',
        'Findlay',
        'Huntington-Ashland',
        'Lima',
        'Mansfield',
        'New Philadelphia-Dover',
        'Portsmouth',
        'Salem',
        'Sandusky',
        'Springfield',
        'Toledo',
        'Weirton-Steubenville',
        'Wheeling',
        'Wooster',
        'Youngstown-Warren-Boardman',
        'Zanesville',
    ],
    'Oklahoma': [
        'Fort Smith',
        'Lawton',
        'Oklahoma City',
        'Stillwater',
        'Tulsa',
    ],
    'Oregon': [
        'Albany-Lebanon',
        'Bend',
        'Corvallis',
        'Eugene-Springfield',
        'Grants Pass',
        'Hermiston-Pendleton',
        'Medford',
        'Portland-Vancouver-Hillsboro',
        'Roseburg',
        'Salem',
    ],
    'Pennsylvania': [
        'Allentown-Bethlehem-Easton',
        'Altoona',
        'Bloomsburg-Berwick',
        'Chambersburg-Waynesboro',
        'DuBois',
        'East Stroudsburg',
        'Erie',
        'Gettysburg',
        'Harrisburg-Carlisle',
        'Indiana',
        'Johnstown',
        'Lancaster',
        'Lebanon',
        'Meadville',
        'New Castle',
        'New York-Newark-Jersey City',
        'Philadelphia-Camden-Wilmington',
        'Pittsburgh',
        'Pottsville',
        'Reading',
        'Scranton--Wilkes-Barre',
        'Somerset',
        'State College',
        'Sunbury',
        'Williamsport',
        'York-Hanover',
        'Youngstown-Warren-Boardman',
    ],
    'Rhode Island': [
        'Providence-Warwick',
    ],
    'South Carolina': [
        'Augusta-Richmond County',
        'Charleston-North Charleston',
        'Charlotte-Concord-Gastonia',
        'Columbia',
        'Florence',
        'Greenville-Anderson',
        'Greenwood',
        'Hilton Head Island-Bluffton',
        'Myrtle Beach-Conway-North Myrtle Beach',
        'Orangeburg',
        'Seneca',
        'Spartanburg',
        'Sumter',
    ],
    'South Dakota': [
        'Rapid City',
        'Sioux City',
        'Sioux Falls',
    ],
    'Tennessee': [
        'Chattanooga',
        'Clarksville',
        'Cleveland',
        'Cookeville',
        'Jackson',
        'Johnson City',
        'Kingsport-Bristol',
        'Knoxville',
        'Memphis',
        'Morristown',
        'Nashville-Davidson--Murfreesboro--Franklin',
        'Sevierville',
        'Tullahoma-Manchester',
    ],
    'Texas': [
        'Abilene',
        'Amarillo',
        'Athens',
        'Austin-Round Rock-Georgetown',
        'Beaumont-Port Arthur',
        'Brownsville-Harlingen',
        'College Station-Bryan',
        'Corpus Christi',
        'Dallas-Fort Worth-Arlington',
        'El Paso',
        'Houston-The Woodlands-Sugar Land',
        'Huntsville',
        'Killeen-Temple',
        'Laredo',
        'Longview',
        'Lubbock',
        'Lufkin',
        'McAllen-Edinburg-Mission',
        'Midland',
        'Odessa',
        'San Angelo',
        'San Antonio-New Braunfels',
        'Sherman-Denison',
        'Texarkana',
        'Tyler',
        'Victoria',
        'Waco',
        'Wichita Falls',
    ],
    'Utah': [
        'Logan',
        'Ogden-Clearfield',
        'Provo-Orem',
        'St. George',
        'Salt Lake City',
    ],
    'Virginia': [
        'Blacksburg-Christiansburg',
        'Bluefield',
        'Charlottesville',
        'Danville',
        'Harrisonburg',
        'Kingsport-Bristol',
        'Lynchburg',
        'Richmond',
        'Roanoke',
        'Staunton',
        'Virginia Beach-Norfolk-Newport News',
        'Winchester',
    ],
    'Vermont': [
        'Burlington-South Burlington',
    ],
    'Washington': [
        'Aberdeen',
        'Bellingham',
        'Bremerton-Silverdale-Port Orchard',
        'Centralia',
        'Kennewick-Richland',
        'Longview',
        'Moses Lake',
        'Mount Vernon-Anacortes',
        'Oak Harbor',
        'Olympia-Lacey-Tumwater',
        'Port Angeles',
        'Portland-Vancouver-Hillsboro',
        'Seattle-Tacoma-Bellevue',
        'Spokane-Spokane Valley',
        'Wenatchee',
        'Yakima',
    ],
    'Wisconsin': [
        'Appleton',
        'Beaver Dam',
        'Chicago-Naperville-Elgin',
        'Duluth',
        'Eau Claire',
        'Fond du Lac',
        'Green Bay',
        'Janesville-Beloit',
        'La Crosse-Onalaska',
        'Madison',
        'Manitowoc',
        'Milwaukee-Waukesha',
        'Minneapolis-St. Paul-Bloomington',
        'Oshkosh-Neenah',
        'Racine',
        'Sheboygan',
        'Watertown-Fort Atkinson',
        'Wausau-Weston',
        'Whitewater',
        'Wisconsin Rapids-Marshfield',
    ],
    'West Virginia': [
        'Beckley',
        'Bluefield',
        'Charleston',
        'Clarksburg',
        'Cumberland',
        'Hagerstown-Martinsburg',
        'Huntington-Ashland',
        'Morgantown',
        'Parkersburg-Vienna',
        'Washington-Arlington-Alexandria',
        'Weirton-Steubenville',
        'Wheeling',
        'Winchester',
    ],
    'Wyoming': [
        'Casper',
        'Cheyenne',
    ],
    'District of Columbia': [
        'Washington-Arlington-Alexandria',
    ],
}

US_STATES = list(METROS.keys())


STATE_ABBREV = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',
    'DC': 'District of Columbia',
}



if __name__ == '__main__':
    pass
